# Generated by Django 2.0.1 on 2018-09-22 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('on', models.BooleanField(default=False)),
                ('connector', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intermediary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('user', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('on_demand', models.BooleanField(default=False)),
                ('time_condition', models.BooleanField(default=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('days', models.CharField(blank=True, max_length=20, null=True)),
                ('value_condition', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SceneActions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=50)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Artifact')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions', to='HomeAutomation.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='SSHConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('script', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('artifactType', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.ArtifactType')),
            ],
        ),
        migrations.CreateModel(
            name='StateVariable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50, null=True)),
                ('typeUI', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=50, null=True)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=1)),
                ('scale', models.IntegerField(default=1)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variables', to='HomeAutomation.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('question', models.CharField(max_length=100, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariableRange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(default=0, max_length=50)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ranges', to='HomeAutomation.StateVariable')),
            ],
        ),
        migrations.CreateModel(
            name='WSConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('artifactType', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.ArtifactType')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=40, null=True)),
                ('pin', models.IntegerField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('intermediary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Intermediary')),
            ],
        ),
        migrations.AddField(
            model_name='sceneactions',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Zone'),
        ),
        migrations.AddField(
            model_name='scene',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Zone'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='intermediary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Intermediary'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.ArtifactType'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Zone'),
        ),
    ]
