# Generated by Django 2.0.1 on 2018-09-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0004_auto_20180830_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='initial_time',
        ),
        migrations.AddField(
            model_name='scene',
            name='days',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='time_condition',
            field=models.BooleanField(default=False),
        ),
    ]
