# Generated by Django 2.0.1 on 2018-06-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0005_auto_20180520_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booleanvariable',
            old_name='on',
            new_name='bool',
        ),
        migrations.AddField(
            model_name='artifact',
            name='onoff',
            field=models.BooleanField(default=False),
        ),
    ]
