# Generated by Django 2.0.1 on 2018-09-08 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0005_auto_20180906_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneactions',
            name='artifact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Artifact'),
        ),
        migrations.AddField(
            model_name='sceneactions',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Zone'),
        ),
        migrations.AlterField(
            model_name='sceneactions',
            name='variable',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.StateVariable'),
        ),
    ]
