# Generated by Django 2.0.1 on 2018-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0006_auto_20180908_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneactions',
            name='variable',
            field=models.IntegerField(default=0),
        ),
    ]
