# Generated by Django 2.0.2 on 2018-06-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0007_auto_20180605_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('end_time', models.DateTimeField(null=True)),
                ('initial_time', models.DateTimeField(null=True)),
                ('frequency', models.CharField(max_length=20)),
                ('on_demand', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SceneActions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Scene')),
            ],
        ),
        migrations.RenameField(
            model_name='artifact',
            old_name='onoff',
            new_name='power',
        ),
        migrations.AddField(
            model_name='statevariable',
            name='typeUI',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statevariable',
            name='artifact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Artifact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statevariable',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statevariable',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statevariable',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='sceneactions',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.StateVariable'),
        ),
    ]
