# Generated by Django 2.0.1 on 2018-07-07 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0008_auto_20180611_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='intermediary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HomeAutomation.Intermediary'),
        ),
        migrations.AddField(
            model_name='zone',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sceneactions',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions', to='HomeAutomation.Scene'),
        ),
    ]
