# Generated by Django 2.0.1 on 2018-07-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0010_auto_20180707_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
